### ISSUE TITLE
How does SSR work?

### ISSUE THREAD

**Issue by mbrochh** [antonybudianto/react-swc-kits#1]
I created a project with react-swc-kits and browsed to localhost:3000 -- this works great.

But when I disable JavaScript in my browser, I just get a blank page.

Are there any extra steps that need to be taken to enable SSR?

**Comment by antonybudianto** [comment]
hi, may I know which command do you use?

I tried using `yarn temp:start` and you will at least get this:
<img width="195" alt="Screen Shot 2021-10-27 at 10 36 38 AM" src="https://user-images.githubusercontent.com/7658554/138995786-8ed7fb55-a466-4e90-bd7b-44e266061a8a.png">


Also one note, currently SSR with loadable is not working due to no plugin support
